### PR TITLE
Updated to 1.9

### PR DESCRIPTION
**Pull request by kimfy**

### CODE REVIEW

**Comment by squeek502** [comment]
Nice work. I've added you as a collaborator, so go ahead and merge this whenever you'd like. 

Are you also kimfy on CurseForge? I can give you access to the CurseForge project as well.

**Comment by kimfy** [comment]
Thank you. I am indeed kimfy there too, here's a [link](http://minecraft.curseforge.com/members/kimfy) just to be safe.

**Comment by squeek502** [comment]
Alright, added you as a contributor on CurseForge: http://minecraft.curseforge.com/projects/creative-blocks

Let me know if you make a new thread on minecraftforum.net and I'll link to it from [mine](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2350111-creative-blocks-creative-building-in-survival-for).

**Comment by kimfy** [comment]
Ok, I might do that at some point, I'll let you know if I do.

**Pull request merged**
